In [2]:
import torch
x = torch.rand(5,3)
print(x)
print(x.view(3,5))
print(x-1)

'''
item()将标量的tensor改为python的数据
'''
x = torch.randn(1)
print(x)
print(x.item())


tensor([[0.0478, 0.7688, 0.0158],
        [0.6047, 0.0541, 0.7140],
        [0.9257, 0.2534, 0.9822],
        [0.0310, 0.4202, 0.1579],
        [0.4394, 0.2892, 0.6205]])
tensor([[0.0478, 0.7688, 0.0158, 0.6047, 0.0541],
        [0.7140, 0.9257, 0.2534, 0.9822, 0.0310],
        [0.4202, 0.1579, 0.4394, 0.2892, 0.6205]])
tensor([[-0.9522, -0.2312, -0.9842],
        [-0.3953, -0.9459, -0.2860],
        [-0.0743, -0.7466, -0.0178],
        [-0.9690, -0.5798, -0.8421],
        [-0.5606, -0.7108, -0.3795]])
tensor([1.0283])
1.028256893157959


In [3]:

'''广播技术,当两个不相等的Tensor相加会使用广播复制成相等的tensor相加'''
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [4]:
#创建一个tensor并设置requires_grad=True
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)
#进行运算操作
y = x + 2
print(y)
print(y.grad_fn)
#x是直接创建的，因此x的grad_fn值为None，凡是直接创建的tensor都是叶子节点
print(x.is_leaf, y.is_leaf)
z = y * y * 3
out = z.mean()
print(z)
print(out.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
True False
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [5]:
a = torch.randn(2, 2) # 􁗌􀥦􀰘􀙭􀓥􁼕􁦊 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad) # False
a.requires_grad_(True)
print(a.requires_grad) # True
b = (a * a).sum()
print(b.grad_fn)



False
True


In [6]:
'''梯度'''
#因为out是一个标量，所以使用backward()时不需要指定求导变量
print(out.backward())




None


In [7]:
print(x.grad)



tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [8]:
out2 = x.sum()
print(out2)
out2.backward()
print(x.grad)
out3 = x.sum()
print(out3)
out3.backward()

print(x.grad)




tensor(4., grad_fn=<SumBackward0>)
tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor(4., grad_fn=<SumBackward0>)
tensor([[6.5000, 6.5000],
        [6.5000, 6.5000]])


In [9]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
out = (x+x).pow(2)

print(out)
y1=out.sum()
# y1.retain_grad()
y1.backward(retain_graph=True)
print(x.grad)
# x.grad.data.zero_()
y=out.sum()
y.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4., 4.],
        [4., 4.]], grad_fn=<PowBackward0>)
tensor([[8., 8.],
        [8., 8.]])
tensor([[16., 16.],
        [16., 16.]])


In [10]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
# print(z)
# v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
# z.backward(v)
# print(x.grad)
w=torch.tensor([[1.0, 0.1], [0.01, 0.001]])
a=torch.sum(z * w)
a.backward()
#上下俩时一样的

v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [11]:
x = torch.tensor(torch.randn(3), requires_grad=True)
y = torch.tensor(torch.randn(3), requires_grad=True)
z = torch.tensor(torch.randn(3), requires_grad=True)
print(x,'\n',y,'\n',z)
t=x+y
print(torch.t(t).shape,z.shape)
l=t.dot(z)
l.backward(retain_graph=True)

print(x.grad)
print(y.grad)
print(z)
print(z.grad)
print(t)


D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  
D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([-1.4494, -1.3544, -0.5127], requires_grad=True) 
 tensor([ 0.5978, -0.3877, -1.1484], requires_grad=True) 
 tensor([ 0.4974,  0.1545, -0.7169], requires_grad=True)
torch.Size([3]) torch.Size([3])
tensor([ 0.4974,  0.1545, -0.7169])
tensor([ 0.4974,  0.1545, -0.7169])
tensor([ 0.4974,  0.1545, -0.7169], requires_grad=True)
tensor([-0.8515, -1.7420, -1.6611])
tensor([-0.8515, -1.7420, -1.6611], grad_fn=<AddBackward0>)


In [12]:
a=torch.ones(2,2)
out=(a+a).pow(2).sum()
out.backward()
print(a.grad)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [13]:
a = torch.randn(2, 2) # 􁗌􀥦􀰘􀙭􀓥􁼕􁦊 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad) # False
a.requires_grad_(True)
print(a.requires_grad) # True
b = (a * a).sum()
print(b.grad_fn)



False
True


In [14]:
'''梯度'''
#因为out是一个标量，所以使用backward()时不需要指定求导变量
print(out.backward())




RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [15]:
print(x.grad)



tensor([ 0.4974,  0.1545, -0.7169])


In [16]:

out2 = x.sum()
print(out2)
out2.backward()
print(x.grad)
out3 = x.sum()
print(out3)
out3.backward()

print(x.grad)




tensor(-3.3164, grad_fn=<SumBackward0>)
tensor([1.4974, 1.1545, 0.2831])
tensor(-3.3164, grad_fn=<SumBackward0>)
tensor([2.4974, 2.1545, 1.2831])


In [17]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
out = (x+x).pow(2)

print(out)
y1=out.sum()
# y1.retain_grad()
y1.backward(retain_graph=True)
print(x.grad)
# x.grad.data.zero_()
y=out.sum()
y.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4., 4.],
        [4., 4.]], grad_fn=<PowBackward0>)
tensor([[8., 8.],
        [8., 8.]])
tensor([[16., 16.],
        [16., 16.]])


In [18]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
# print(z)
# v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
# z.backward(v)
# print(x.grad)
w=torch.tensor([[1.0, 0.1], [0.01, 0.001]])
a=torch.sum(z * w)
a.backward()
#上下俩时一样的

v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [19]:
x = torch.tensor(torch.randn(3), requires_grad=True)
y = torch.tensor(torch.randn(3), requires_grad=True)
z = torch.tensor(torch.randn(3), requires_grad=True)
print(x,'\n',y,'\n',z)
t=x+y
print(torch.t(t).shape,z.shape)
l=t.dot(z)
l.backward(retain_graph=True)

print(x.grad)
print(y.grad)
print(z)
print(z.grad)
print(t)


D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  
D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([-1.0405, -1.7219, -0.4722], requires_grad=True) 
 tensor([-1.2998, -0.4951, -0.4692], requires_grad=True) 
 tensor([-1.1694, -2.4005,  0.5344], requires_grad=True)
torch.Size([3]) torch.Size([3])
tensor([-1.1694, -2.4005,  0.5344])
tensor([-1.1694, -2.4005,  0.5344])
tensor([-1.1694, -2.4005,  0.5344], requires_grad=True)
tensor([-2.3403, -2.2170, -0.9414])
tensor([-2.3403, -2.2170, -0.9414], grad_fn=<AddBackward0>)


In [20]:
a=torch.ones(2,2,requires_grad=True)
out=(a+a).pow(2).sum()
out.backward()
print(a.grad)


tensor([[8., 8.],
        [8., 8.]])


In [21]:
(3.14-2.33)**2+(1.07-0.98)**2+(1.23-1.32)**2



0.6723000000000001

In [22]:

a = torch.randn(2, 2) # 􁗌􀥦􀰘􀙭􀓥􁼕􁦊 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad) # False
a.requires_grad_(True)
print(a.requires_grad) # True
b = (a * a).sum()
print(b.grad_fn)



False
True


In [23]:
'''梯度'''
#因为out是一个标量，所以使用backward()时不需要指定求导变量
print(out.backward())




RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [24]:
print(x.grad)



tensor([-1.1694, -2.4005,  0.5344])


In [25]:
out2 = x.sum()
print(out2)
out2.backward()
print(x.grad)
out3 = x.sum()
print(out3)
out3.backward()

print(x.grad)




tensor(-3.2346, grad_fn=<SumBackward0>)
tensor([-0.1694, -1.4005,  1.5344])
tensor(-3.2346, grad_fn=<SumBackward0>)
tensor([ 0.8306, -0.4005,  2.5344])


In [26]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
out = (x+x).pow(2)

print(out)
y1=out.sum()
# y1.retain_grad()
y1.backward(retain_graph=True)
print(x.grad)
# x.grad.data.zero_()
y=out.sum()
y.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4., 4.],
        [4., 4.]], grad_fn=<PowBackward0>)
tensor([[8., 8.],
        [8., 8.]])
tensor([[16., 16.],
        [16., 16.]])


In [27]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
# print(z)
# v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
# z.backward(v)
# print(x.grad)
w=torch.tensor([[1.0, 0.1], [0.01, 0.001]])
a=torch.sum(z * w)
a.backward()
#上下俩时一样的

v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [28]:

x = torch.tensor(torch.randn(3), requires_grad=True)
y = torch.tensor(torch.randn(3), requires_grad=True)
z = torch.tensor(torch.randn(3), requires_grad=True)
print(x,'\n',y,'\n',z)
t=x+y
print(torch.t(t).shape,z.shape)
l=t.dot(z)
l.backward(retain_graph=True)

print(x.grad)
print(y.grad)
print(z)
print(z.grad)
print(t)


D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  
D:\programming\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([-0.2297, -0.1802, -1.3488], requires_grad=True) 
 tensor([ 0.0295, -0.4125,  2.0169], requires_grad=True) 
 tensor([ 0.3014, -0.9879, -1.0260], requires_grad=True)
torch.Size([3]) torch.Size([3])
tensor([ 0.3014, -0.9879, -1.0260])
tensor([ 0.3014, -0.9879, -1.0260])
tensor([ 0.3014, -0.9879, -1.0260], requires_grad=True)
tensor([-0.2002, -0.5927,  0.6681])
tensor([-0.2002, -0.5927,  0.6681], grad_fn=<AddBackward0>)


In [29]:
a=torch.ones(2,2,requires_grad=True)
out=(a+a).pow(2).sum()
out.backward()
print(a.grad)


tensor([[8., 8.],
        [8., 8.]])


In [30]:
c=((3.14-2.33)**2+(1.07-0.98)**2+(1.23-1.32)**2)/3
print(c)

0.22410000000000005


In [ ]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2
print(x.requires_grad)
print(y1, y1.requires_grad) # True
print(y2, y2.requires_grad) # False
print(y3, y3.requires_grad) # True
y3.backward()
print(x.grad)


In [ ]:
x = torch.ones(1,requires_grad=True)
print(x.data) # 􁬮􀸎􀓞􀓻tensor
print(x.data.requires_grad) # 􀖕􀸎􀫪􁕪􀸎􁇿􁒈􀔭􁦇􁓒􀢶􀔏􀥘
y = 2 * x
x.data *= 100 # 􀝝􀶯􀝒􀔧􊧊􀒅􀓧􀕿􁦕􀭯􀣁􁦇􁓒􀢶􀒅􀲅􀕦􀓧􀕿􀭽􀟥􀼀􀬶􀖃􀶎
y.backward()
print(x) # 􀹅􀶯data􁌱􊧊􀔞􀕿􀭽􀟥tensor􁌱􊧊
print(x.grad)

In [ ]:
y=torch.tensor([1,2,3,4,5])
print(y)
print(y.view(-1,1))

In [ ]:
import sys
sys.path.append("./dlzh") 
# import d2lzh_pytorch as d2l

import dlzh.d2lzh_pytorch as d2l



In [ ]:
import sys
sys.path.append("./dlzh") 
# import d2lzh_pytorch as d2l

import dlzh.d2lzh_pytorch as d2l



In [ ]:
x = torch.ones(1,requires_grad=True)
print(x.data) # 􁬮􀸎􀓞􀓻tensor
print(x.data.requires_grad) # 􀖕􀸎􀫪􁕪􀸎􁇿􁒈􀔭􁦇􁓒􀢶􀔏􀥘
y = 2 * x
x.data *= 100 # 􀝝􀶯􀝒􀔧􊧊􀒅􀓧􀕿􁦕􀭯􀣁􁦇􁓒􀢶􀒅􀲅􀕦􀓧􀕿􀭽􀟥􀼀􀬶􀖃􀶎
y.backward()
print(x) # 􀹅􀶯data􁌱􊧊􀔞􀕿􀭽􀟥tensor􁌱􊧊
print(x.grad)

In [ ]:
y=torch.tensor([1,2,3,4,5])
print(y)
print(y.view(-1,1))




In [ ]:
print(60000%256)


In [ ]:
print(60000%256)


In [ ]:
x = torch.ones(1,requires_grad=True)
print(x.data) # 􁬮􀸎􀓞􀓻tensor
print(x.data.requires_grad) # 􀖕􀸎􀫪􁕪􀸎􁇿􁒈􀔭􁦇􁓒􀢶􀔏􀥘
y = 2 * x
x.data *= 100 # 􀝝􀶯􀝒􀔧􊧊􀒅􀓧􀕿􁦕􀭯􀣁􁦇􁓒􀢶􀒅􀲅􀕦􀓧􀕿􀭽􀟥􀼀􀬶􀖃􀶎
y.backward()
print(x) # 􀹅􀶯data􁌱􊧊􀔞􀕿􀭽􀟥tensor􁌱􊧊
print(x.grad)

In [ ]:
y=torch.tensor([1,2,3,4,5])
print(y)
print(y.view(-1,1))




In [ ]:
print(60000%256)


In [ ]:
print(60000%256)


In [ ]:
x = torch.ones(1,requires_grad=True)
print(x.data) # 􁬮􀸎􀓞􀓻tensor
print(x.data.requires_grad) # 􀖕􀸎􀫪􁕪􀸎􁇿􁒈􀔭􁦇􁓒􀢶􀔏􀥘
y = 2 * x
x.data *= 100 # 􀝝􀶯􀝒􀔧􊧊􀒅􀓧􀕿􁦕􀭯􀣁􁦇􁓒􀢶􀒅􀲅􀕦􀓧􀕿􀭽􀟥􀼀􀬶􀖃􀶎
y.backward()
print(x) # 􀹅􀶯data􁌱􊧊􀔞􀕿􀭽􀟥tensor􁌱􊧊
print(x.grad)

In [ ]:
y=torch.tensor([1,2,3,4,5])
print(y)
print(y.view(-1,1))




In [ ]:
print(60000%256)


In [ ]:
print(60000%256)


In [ ]:
x = torch.ones(1,requires_grad=True)
print(x.data) # 􁬮􀸎􀓞􀓻tensor
print(x.data.requires_grad) # 􀖕􀸎􀫪􁕪􀸎􁇿􁒈􀔭􁦇􁓒􀢶􀔏􀥘
y = 2 * x
x.data *= 100 # 􀝝􀶯􀝒􀔧􊧊􀒅􀓧􀕿􁦕􀭯􀣁􁦇􁓒􀢶􀒅􀲅􀕦􀓧􀕿􀭽􀟥􀼀􀬶􀖃􀶎
y.backward()
print(x) # 􀹅􀶯data􁌱􊧊􀔞􀕿􀭽􀟥tensor􁌱􊧊
print(x.grad)

In [ ]:
y=torch.tensor([1,2,3,4,5])
print(y)
print(y.view(-1,1))




In [ ]:
print(60000%256)


In [35]:
print(60000%256)


True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True
tensor(2.)


In [38]:
x = torch.ones(1,requires_grad=True)
print(x.data) # 􁬮􀸎􀓞􀓻tensor
print(x.data.requires_grad) # 􀖕􀸎􀫪􁕪􀸎􁇿􁒈􀔭􁦇􁓒􀢶􀔏􀥘
y = 2 * x
x.data *= 100 # 􀝝􀶯􀝒􀔧􊧊􀒅􀓧􀕿􁦕􀭯􀣁􁦇􁓒􀢶􀒅􀲅􀕦􀓧􀕿􀭽􀟥􀼀􀬶􀖃􀶎
y.backward()
print(x) # 􀹅􀶯data􁌱􊧊􀔞􀕿􀭽􀟥tensor􁌱􊧊
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])


In [1]:
y=torch.tensor([1,2,3,4,5])
print(y)
print(y.view(-1,1))




NameError: name 'torch' is not defined

In [2]:
print(60000%256)


96
